[package]
name = "subtile"
version = "0.1.5"
edition = "2021"
description = "A crate of utils to operate traitements on subtitles"
repository = "https://github.com/gwen-lg/subtile"
authors = ["Eric Kidd <git@randomhacks.net>", "Gwen Lg <me@gwenlg.fr>"]
keywords = ["subtitle", "library", "parse", "write", "vobsub"]
categories = [
    "command-line-utilities",
    "encoding",
    "multimedia::encoding",
    "parser-implementations",
]
license = "LGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
cargo = { priority = -1, level = "warn" }
complexity = { priority = -1, level = "deny" }
correctness = { priority = -1, level = "deny" }
# nursery = { priority = -1, level = "deny" }
# pedantic = { priority = -1, level = "warn" }
perf = { priority = -1, level = "deny" }
# restriction  = { priority = -1, level = "deny" }
style = { priority = -1, level = "deny" }
# suspicious = { priority = -1, level = "deny" }

[dependencies]
cast = "0.3"
image = { version = "0.25", default-features = false }
log = "0.4"
nom = "7.1"
once_cell = "1.19"
profiling = "1.0"
regex = "1.10"
safemem = "0.3"
thiserror = "1.0"

[dev-dependencies]
env_logger = "0.11"
glob = "0.3"
