[package]
name = "subtile"
version = "0.1.0"
edition = "2021"
description = "A crate of utils to operate traitements on subtitles"
repository = "https://github.com/gwen-lg/subtile"
keywords = ["subtitle", "library", "parse", "write", "vobsub"]
categories = ["command-line-utilities", "encoding", "multimedia::encoding", "parser-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cast = "0.3.0"
#common_failures = { version = "0.1", path = "../common_failures" }
failure = "0.1.1"
image = { version = "0.24.7", default-features = false }
log = "0.4.20"
nom = "2.1.0, <2.2.0"
once_cell = "1.19"
regex = "1.10.2"
safemem = "0.3.3"

[dev-dependencies]
env_logger = "0.11.1"
glob = "0.3.1"
