[package]
name = "subtile"
version = "0.1.0"
edition = "2021"
description = "A crate of utils to operate traitements on subtitles"
repository = "https://github.com/gwen-lg/subtile"
keywords = ["subtitle", "library", "parse", "write", "vobsub"]
categories = ["command-line-utilities", "encoding", "multimedia::encoding", "parser-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cast = "0.2.0"
#common_failures = { version = "0.1", path = "../common_failures" }
failure = "0.1.1"
image = { version = "0.18.0", default-features = false }
lazy_static = "1.0"
log = "0.3.6"
nom = "2.1.0, <2.2.0"
regex = "0.2.1"
safemem = "0.2.0"

[dev-dependencies]
env_logger = "0.4.0"
glob = "0.2.11"
