[package]
name = "subtile"
version = "0.1.0"
edition = "2021"
description = "A crate of utils to operate traitements on subtitles"
repository = "https://github.com/gwen-lg/subtile"
keywords = ["subtitle", "library", "parse", "write", "vobsub"]
categories = ["command-line-utilities", "encoding", "multimedia::encoding", "parser-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cast = "0.3.0"
image = { version = "0.24.7", default-features = false }
log = "0.4.20"
nom = "7.1.3"
once_cell = "1.19"
regex = "1.10.2"
safemem = "0.3.3"
thiserror = "1.0.51"

[dev-dependencies]
env_logger = "0.11.1"
glob = "0.3.1"
